export const CHAIN_LIST = [
    { fetchedChainName: 'valobit', chainId: null, chainName: null },
    { fetchedChainName: 'arbitrum-nova', chainId: 42170, chainName: null },
    { fetchedChainName: 'factom', chainId: null, chainName: null },
    { fetchedChainName: 'mantra', chainId: null, chainName: null },
    { fetchedChainName: 'monad', chainId: null, chainName: null },
    { fetchedChainName: 'kusama', chainId: null, chainName: null },
    { fetchedChainName: 'zano', chainId: null, chainName: null },
    { fetchedChainName: 'picasso', chainId: null, chainName: null },
    { fetchedChainName: 'findora', chainId: null, chainName: null },
    { fetchedChainName: 'bitkub-chain', chainId: 96, chainName: null },
    { fetchedChainName: 'onus', chainId: null, chainName: null },
    { fetchedChainName: 'empire', chainId: 3693, chainName: null },
    { fetchedChainName: 'areon-network', chainId: null, chainName: null },
    { fetchedChainName: 'shibarium', chainId: null, chainName: null },
    { fetchedChainName: 'kujira', chainId: null, chainName: null },
    { fetchedChainName: 'vite', chainId: null, chainName: null },
    { fetchedChainName: 'komodo', chainId: null, chainName: null },
    { fetchedChainName: 'counterparty', chainId: null, chainName: null },
    { fetchedChainName: 'bitshares', chainId: null, chainName: null },
    { fetchedChainName: 'hoo', chainId: null, chainName: null },
    { fetchedChainName: 'icon', chainId: null, chainName: null },
    { fetchedChainName: 'nem', chainId: null, chainName: null },
    { fetchedChainName: 'nuls', chainId: null, chainName: null },
    { fetchedChainName: 'super-zero', chainId: null, chainName: null },
    { fetchedChainName: 'yocoin', chainId: null, chainName: null },
    { fetchedChainName: 'internet-computer', chainId: null, chainName: null },
    { fetchedChainName: 'exosama', chainId: null, chainName: null },
    { fetchedChainName: 'taiko', chainId: 167000, chainName: 'taiko' },
    { fetchedChainName: 'godwoken', chainId: null, chainName: null },
    { fetchedChainName: 'trustless-computer', chainId: null, chainName: null },
    { fetchedChainName: 'neutron', chainId: null, chainName: null },
    { fetchedChainName: 'bahamut', chainId: 5165, chainName: null },
    { fetchedChainName: 'etherlink', chainId: 42793, chainName: null },
    { fetchedChainName: 'cybria', chainId: 6661, chainName: null },
    { fetchedChainName: 'alienx', chainId: 10241024, chainName: null },
    { fetchedChainName: 'omax', chainId: 311, chainName: null },
    { fetchedChainName: 'xodex', chainId: 2415, chainName: null },
    { fetchedChainName: 'celestia', chainId: null, chainName: null },
    { fetchedChainName: 'cardano', chainId: null, chainName: null },
    { fetchedChainName: 'aura-network', chainId: null, chainName: null },
    { fetchedChainName: 'echelon', chainId: null, chainName: null },
    { fetchedChainName: 'acala', chainId: null, chainName: null },
    { fetchedChainName: 'everscale', chainId: null, chainName: null },
    { fetchedChainName: 'degen', chainId: 666666666, chainName: null },
    { fetchedChainName: 'lisk', chainId: 1135, chainName: null },
    { fetchedChainName: 'telos', chainId: 40, chainName: null },
    { fetchedChainName: 'saga', chainId: null, chainName: null },
    { fetchedChainName: 'zenon', chainId: null, chainName: null },
    {
        fetchedChainName: 'defi-kingdoms-blockchain',
        chainId: 53935,
        chainName: null,
    },
    { fetchedChainName: 'tron', chainId: null, chainName: 'tronMainnet' },
    { fetchedChainName: 'rootstock', chainId: 30, chainName: 'rootstock' },
    { fetchedChainName: 'titanchain', chainId: 18888, chainName: null },
    { fetchedChainName: 'omnia', chainId: 2342, chainName: null },
    { fetchedChainName: 'tombchain', chainId: null, chainName: null },
    { fetchedChainName: 'callisto', chainId: null, chainName: null },
    { fetchedChainName: 'function-x', chainId: 530, chainName: null },
    { fetchedChainName: 'redlight-chain', chainId: 2611, chainName: null },
    { fetchedChainName: 'alephium', chainId: null, chainName: null },
    { fetchedChainName: 'assetmantle', chainId: null, chainName: null },
    { fetchedChainName: 'kardiachain', chainId: 24, chainName: null },
    { fetchedChainName: 'venom', chainId: null, chainName: null },
    { fetchedChainName: 'neon-evm', chainId: 245022934, chainName: null },
    { fetchedChainName: 'genesys-network', chainId: 16507, chainName: null },
    { fetchedChainName: 'okex-chain', chainId: 66, chainName: null },
    { fetchedChainName: 'mint', chainId: 185, chainName: null },
    { fetchedChainName: 'apex', chainId: null, chainName: null },
    { fetchedChainName: 'tezos', chainId: null, chainName: null },
    { fetchedChainName: 'waves', chainId: null, chainName: null },
    { fetchedChainName: 'xai', chainId: 660279, chainName: null },
    { fetchedChainName: 'rari', chainId: 1380012617, chainName: null },
    { fetchedChainName: 'stargaze', chainId: null, chainName: null },
    { fetchedChainName: 'nxt', chainId: null, chainName: null },
    { fetchedChainName: 'mdex', chainId: null, chainName: null },
    {
        fetchedChainName: 'harmony-shard-0',
        chainId: 1666600000,
        chainName: null,
    },
    { fetchedChainName: 'humanode', chainId: null, chainName: null },
    { fetchedChainName: 'curio-chain', chainId: null, chainName: null },
    { fetchedChainName: 'kava', chainId: 2222, chainName: null },
    { fetchedChainName: 'zkfair', chainId: null, chainName: null },
    { fetchedChainName: 'opbnb', chainId: 204, chainName: null },
    { fetchedChainName: 'quicksilver', chainId: null, chainName: null },
    { fetchedChainName: 'matrix', chainId: null, chainName: null },
    { fetchedChainName: 'ShibChain', chainId: null, chainName: null },
    { fetchedChainName: 'fusion-network', chainId: null, chainName: null },
    { fetchedChainName: 'libre', chainId: null, chainName: null },
    { fetchedChainName: 'gochain', chainId: null, chainName: null },
    { fetchedChainName: 'achain', chainId: null, chainName: null },
    { fetchedChainName: 'omni', chainId: null, chainName: null },
    { fetchedChainName: 'enq-enecuum', chainId: null, chainName: null },
    { fetchedChainName: 'metaverse-etp', chainId: null, chainName: null },
    { fetchedChainName: 'ardor', chainId: null, chainName: null },
    { fetchedChainName: 'stratis', chainId: null, chainName: null },
    { fetchedChainName: 'openledger', chainId: null, chainName: null },
    { fetchedChainName: 'qtum', chainId: null, chainName: null },
    { fetchedChainName: 'bitcoin-cash', chainId: null, chainName: null },
    { fetchedChainName: 'ontology', chainId: null, chainName: null },
    { fetchedChainName: 'aleph-zero', chainId: null, chainName: null },
    { fetchedChainName: 'syscoin', chainId: 57, chainName: null },
    { fetchedChainName: 'solana', chainId: null, chainName: 'solana' },
    { fetchedChainName: 'drc-20', chainId: null, chainName: null },
    { fetchedChainName: 'zetachain', chainId: 7000, chainName: null },
    { fetchedChainName: 'stellar', chainId: null, chainName: null },
    { fetchedChainName: 'casper-network', chainId: null, chainName: null },
    { fetchedChainName: 'xpla', chainId: null, chainName: null },
    { fetchedChainName: 'karura', chainId: null, chainName: null },
    { fetchedChainName: 'rails-network', chainId: null, chainName: null },
    { fetchedChainName: 'chromia', chainId: null, chainName: null },
    { fetchedChainName: 'cube', chainId: null, chainName: null },
    { fetchedChainName: 'bifrost-network', chainId: null, chainName: null },
    { fetchedChainName: 'metis-andromeda', chainId: 1088, chainName: 'metis' },
    { fetchedChainName: 'neo', chainId: null, chainName: null },
    { fetchedChainName: 'filecoin', chainId: 314, chainName: null },
    { fetchedChainName: 'cellframe', chainId: null, chainName: null },
    { fetchedChainName: 'zilliqa', chainId: null, chainName: null },
    { fetchedChainName: 'beam', chainId: 4337, chainName: null },
    { fetchedChainName: 'hypra-network', chainId: 622277, chainName: null },
    { fetchedChainName: 'thorchain', chainId: null, chainName: null },
    { fetchedChainName: 'sge', chainId: null, chainName: null },
    { fetchedChainName: 'alverychain', chainId: 3797, chainName: null },
    { fetchedChainName: 'binancecoin', chainId: null, chainName: null },
    { fetchedChainName: 'rss3-vsl', chainId: 12553, chainName: null },
    { fetchedChainName: 'theta', chainId: 361, chainName: null },
    { fetchedChainName: 'xdai', chainId: 100, chainName: null },
    { fetchedChainName: 're-al', chainId: 111188, chainName: null },
    { fetchedChainName: 'kasplex', chainId: null, chainName: null },
    { fetchedChainName: 'sx-network', chainId: 416, chainName: null },
    { fetchedChainName: 'osmosis', chainId: null, chainName: 'osmosis' },
    { fetchedChainName: 'ancient8', chainId: 888888888, chainName: null },
    { fetchedChainName: 'akash', chainId: null, chainName: null },
    { fetchedChainName: 'vanar-chain', chainId: 2040, chainName: 'vanar' },
    { fetchedChainName: 'velas', chainId: 106, chainName: null },
    { fetchedChainName: 'noble', chainId: null, chainName: null },
    { fetchedChainName: 'near-protocol', chainId: null, chainName: null },
    { fetchedChainName: 'manta-pacific', chainId: 169, chainName: 'manta' },
    { fetchedChainName: 'meld', chainId: 333000333, chainName: null },
    { fetchedChainName: 'wemix-network', chainId: 1111, chainName: null },
    { fetchedChainName: 'immutable', chainId: 13371, chainName: null },
    { fetchedChainName: 'map-protocol', chainId: 22776, chainName: null },
    { fetchedChainName: 'coinex-smart-chain', chainId: 52, chainName: null },
    { fetchedChainName: 'zora-network', chainId: 7777777, chainName: 'zora' },
    { fetchedChainName: 'merlin-chain', chainId: 4200, chainName: null },
    { fetchedChainName: 'injective', chainId: null, chainName: 'injective' },
    { fetchedChainName: 'defichain-evm', chainId: 1130, chainName: null },
    { fetchedChainName: 'orenium', chainId: null, chainName: null },
    { fetchedChainName: 'beamprivacy', chainId: null, chainName: null },
    { fetchedChainName: 'saita-chain', chainId: 1209, chainName: null },
    { fetchedChainName: 'parex-network', chainId: 322202, chainName: null },
    { fetchedChainName: 'cyber', chainId: 7560, chainName: null },
    { fetchedChainName: 'oasis', chainId: 42262, chainName: null },
    { fetchedChainName: 'funki', chainId: 33979, chainName: null },
    { fetchedChainName: 'ergo', chainId: null, chainName: null },
    { fetchedChainName: 'turan-network', chainId: null, chainName: null },
    { fetchedChainName: 'hoo-smart-chain', chainId: 70, chainName: null },
    { fetchedChainName: 'onchain', chainId: 27563, chainName: null },
    { fetchedChainName: 'abstract', chainId: 2741, chainName: 'abstract' },
    { fetchedChainName: 'ordinals', chainId: null, chainName: null },
    { fetchedChainName: 'juno', chainId: null, chainName: null },
    { fetchedChainName: 'elrond', chainId: null, chainName: null },
    { fetchedChainName: 'Bitcichain', chainId: 1907, chainName: null },
    { fetchedChainName: 'planq-network', chainId: 7070, chainName: null },
    { fetchedChainName: 'bitcanna', chainId: null, chainName: null },
    { fetchedChainName: 'crescent', chainId: null, chainName: null },
    { fetchedChainName: 'mantle', chainId: 5000, chainName: 'mantle' },
    { fetchedChainName: 'core', chainId: 1116, chainName: null },
    { fetchedChainName: 'bouncebit', chainId: 6001, chainName: null },
    { fetchedChainName: 'polis-chain', chainId: 333999, chainName: null },
    { fetchedChainName: 'q-mainnet', chainId: 35441, chainName: null },
    { fetchedChainName: 'mixin-network', chainId: null, chainName: null },
    { fetchedChainName: 'defichain', chainId: null, chainName: null },
    { fetchedChainName: 'ronin', chainId: 2020, chainName: null },
    { fetchedChainName: 'furya', chainId: null, chainName: null },
    { fetchedChainName: 'lightlink', chainId: 1890, chainName: null },
    { fetchedChainName: 'mode', chainId: 34443, chainName: 'mode' },
    { fetchedChainName: 'eos-evm', chainId: 17777, chainName: null },
    { fetchedChainName: 'ultron', chainId: 1231, chainName: null },
    { fetchedChainName: 'tenet', chainId: 1559, chainName: null },
    { fetchedChainName: 'comdex', chainId: null, chainName: null },
    { fetchedChainName: 'ethereum', chainId: 1, chainName: 'ethereum' },
    { fetchedChainName: 'rollux', chainId: 570, chainName: 'rollux' },
    { fetchedChainName: 'canto', chainId: 7700, chainName: null },
    { fetchedChainName: 'celer-network', chainId: null, chainName: null },
    { fetchedChainName: 'loopring', chainId: null, chainName: null },
    { fetchedChainName: 'chiliz', chainId: null, chainName: null },
    { fetchedChainName: 'flare-network', chainId: 14, chainName: null },
    { fetchedChainName: 'clover', chainId: null, chainName: null },
    { fetchedChainName: 'bifrost-kusama', chainId: null, chainName: null },
    { fetchedChainName: 'ki-chain', chainId: null, chainName: null },
    { fetchedChainName: 'songbird', chainId: 19, chainName: null },
    { fetchedChainName: 'shido', chainId: 9008, chainName: 'shido' },
    { fetchedChainName: 'artela', chainId: 11820, chainName: null },
    {
        fetchedChainName: 'optimistic-ethereum',
        chainId: 10,
        chainName: 'optimism',
    },
    { fetchedChainName: 'linea', chainId: 59144, chainName: 'linea' },
    { fetchedChainName: 'eclipse', chainId: null, chainName: null },
    { fetchedChainName: 'omniflix', chainId: null, chainName: null },
    { fetchedChainName: 'gravity-bridge', chainId: null, chainName: null },
    { fetchedChainName: 'shimmer_evm', chainId: 148, chainName: null },
    { fetchedChainName: 'elysium', chainId: 1339, chainName: null },
    { fetchedChainName: 'aptos', chainId: null, chainName: 'sui' },
    { fetchedChainName: 'chihuahua', chainId: null, chainName: null },
    { fetchedChainName: 'coreum', chainId: null, chainName: null },
    { fetchedChainName: 'cudos', chainId: null, chainName: null },
    { fetchedChainName: 'desmos', chainId: null, chainName: null },
    { fetchedChainName: 'dydx', chainId: null, chainName: null },
    { fetchedChainName: 'dymension', chainId: null, chainName: null },
    { fetchedChainName: 'iris', chainId: null, chainName: null },
    { fetchedChainName: 'ixo', chainId: null, chainName: null },
    { fetchedChainName: 'kyve', chainId: null, chainName: null },
    { fetchedChainName: 'likecoin', chainId: null, chainName: null },
    { fetchedChainName: 'lum', chainId: null, chainName: null },
    { fetchedChainName: 'mars-protocol', chainId: null, chainName: null },
    { fetchedChainName: 'nibiru', chainId: null, chainName: null },
    { fetchedChainName: 'onomy', chainId: null, chainName: null },
    { fetchedChainName: 'persistence', chainId: null, chainName: null },
    { fetchedChainName: 'quasar', chainId: null, chainName: null },
    { fetchedChainName: 'regen', chainId: null, chainName: null },
    { fetchedChainName: 'sommelier', chainId: null, chainName: null },
    { fetchedChainName: 'stride', chainId: null, chainName: null },
    { fetchedChainName: 'teritori', chainId: null, chainName: null },
    { fetchedChainName: 'ux-chain', chainId: null, chainName: null },
    { fetchedChainName: 'flow-evm', chainId: 747, chainName: null },
    { fetchedChainName: 'mayachain', chainId: null, chainName: null },
    { fetchedChainName: 'galachain', chainId: null, chainName: null },
    { fetchedChainName: 'xt-smart-chain', chainId: 520, chainName: null },
    { fetchedChainName: 'endurance', chainId: 648, chainName: null },
    { fetchedChainName: 'bitgert', chainId: 32520, chainName: null },
    { fetchedChainName: 'stacks', chainId: null, chainName: null },
    { fetchedChainName: 'ham', chainId: 5112, chainName: null },
    { fetchedChainName: 'flow', chainId: null, chainName: null },
    { fetchedChainName: 'ql1', chainId: 766, chainName: null },
    { fetchedChainName: 'fraxtal', chainId: 252, chainName: null },
    { fetchedChainName: 'kadena', chainId: null, chainName: null },
    { fetchedChainName: 'massa', chainId: null, chainName: null },
    { fetchedChainName: 'bitlayer', chainId: 200901, chainName: null },
    { fetchedChainName: 'lukso', chainId: 42, chainName: null },
    { fetchedChainName: 'bevm', chainId: 11501, chainName: null },
    { fetchedChainName: 'tdvv-sidechain', chainId: null, chainName: null },
    { fetchedChainName: 'octaspace', chainId: 800001, chainName: null },
    { fetchedChainName: 'radix', chainId: null, chainName: null },
    { fetchedChainName: 'units-network', chainId: 88811, chainName: null },
    { fetchedChainName: 'blast', chainId: 81457, chainName: 'blast' },
    { fetchedChainName: 'oraichain', chainId: null, chainName: null },
    { fetchedChainName: 'laikachain', chainId: 6942, chainName: null },
    { fetchedChainName: 'berachain', chainId: 80094, chainName: null },
    { fetchedChainName: 'zklink-nova', chainId: 810180, chainName: null },
    { fetchedChainName: 'aurora', chainId: 1313161554, chainName: null },
    { fetchedChainName: 'celo', chainId: 42220, chainName: null },
    { fetchedChainName: 'archway', chainId: null, chainName: null },
    { fetchedChainName: 'the-open-network', chainId: null, chainName: null },
    { fetchedChainName: 'energi', chainId: 39797, chainName: null },
    {
        fetchedChainName: 'polygon-zkevm',
        chainId: 1101,
        chainName: 'polygon_zkevm',
    },
    { fetchedChainName: 'evmos', chainId: 9001, chainName: null },
    { fetchedChainName: 'terra', chainId: null, chainName: null },
    { fetchedChainName: 'secret', chainId: null, chainName: null },
    { fetchedChainName: 'iotex', chainId: 4689, chainName: null },
    { fetchedChainName: 'ink', chainId: 57073, chainName: 'ink' },
    { fetchedChainName: 'astar', chainId: 592, chainName: null },
    { fetchedChainName: 'fuse', chainId: 122, chainName: null },
    { fetchedChainName: 'metal-l2', chainId: null, chainName: null },
    { fetchedChainName: 'jibchain', chainId: 8899, chainName: null },
    { fetchedChainName: 'xdc-network', chainId: 50, chainName: null },
    { fetchedChainName: 'terra-2', chainId: null, chainName: null },
    { fetchedChainName: 'soneium', chainId: 1868, chainName: 'soneium' },
    { fetchedChainName: 'wanchain', chainId: 888, chainName: null },
    { fetchedChainName: 'ethereumpow', chainId: null, chainName: null },
    { fetchedChainName: 'bittorrent', chainId: 199, chainName: null },
    { fetchedChainName: 'elastos', chainId: 20, chainName: null },
    { fetchedChainName: 'smartbch', chainId: 10000, chainName: null },
    { fetchedChainName: 'step-network', chainId: 1234, chainName: null },
    { fetchedChainName: 'migaloo', chainId: null, chainName: null },
    { fetchedChainName: 'hedera-hashgraph', chainId: 295, chainName: null },
    { fetchedChainName: 'thundercore', chainId: 108, chainName: null },
    { fetchedChainName: 'proof-of-memes', chainId: 18159, chainName: null },
    { fetchedChainName: 'mainnetz', chainId: 2016, chainName: null },
    { fetchedChainName: 'hydra', chainId: null, chainName: null },
    { fetchedChainName: 'niza', chainId: null, chainName: null },
    { fetchedChainName: 'uton', chainId: null, chainName: null },
    { fetchedChainName: 'saakuru', chainId: 7225878, chainName: 'saakuru' },
    {
        fetchedChainName: 'hyperliquid',
        chainId: null,
        chainName: 'hyperliquid',
    },
    {
        fetchedChainName: 'oasis-sapphire',
        chainId: 23294,
        chainName: 'oasisSapphire',
    },
    { fetchedChainName: 'hela', chainId: 8668, chainName: null },
    { fetchedChainName: 'iota-evm', chainId: 8822, chainName: null },
    { fetchedChainName: 'nahmii', chainId: 4061, chainName: 'nahmii' },
    { fetchedChainName: 'boba-bnb', chainId: 56288, chainName: null },
    { fetchedChainName: 'zedxion', chainId: 83872, chainName: null },
    { fetchedChainName: 'vyvo-smart-chain', chainId: 8889, chainName: null },
    { fetchedChainName: 'astar-zkevm', chainId: 3776, chainName: null },
    { fetchedChainName: 'oasys', chainId: 248, chainName: null },
    { fetchedChainName: 'milkomeda-cardano', chainId: 2001, chainName: null },
    { fetchedChainName: 'haqq-network', chainId: 11235, chainName: null },
    { fetchedChainName: 'sui', chainId: null, chainName: 'sui' },
    { fetchedChainName: 'sora', chainId: null, chainName: null },
    { fetchedChainName: 'zksync', chainId: 324, chainName: 'zksync' },
    { fetchedChainName: 'bitrock', chainId: 7171, chainName: null },
    { fetchedChainName: 'moonriver', chainId: 1285, chainName: null },
    { fetchedChainName: 'zircuit', chainId: 48900, chainName: null },
    { fetchedChainName: 'boba', chainId: 288, chainName: 'boba' },
    { fetchedChainName: 'morph-l2', chainId: 2818, chainName: 'morph' },
    { fetchedChainName: 'sanko', chainId: 1996, chainName: null },
    { fetchedChainName: 'aelf', chainId: null, chainName: null },
    { fetchedChainName: 'conflux', chainId: 1030, chainName: null },
    { fetchedChainName: 'eos', chainId: null, chainName: null },
    { fetchedChainName: 'ethereum-classic', chainId: 61, chainName: null },
    { fetchedChainName: 'huobi-token', chainId: 128, chainName: null },
    {
        fetchedChainName: 'kucoin-community-chain',
        chainId: 321,
        chainName: null,
    },
    { fetchedChainName: 'qitmeer-network', chainId: 813, chainName: null },
    { fetchedChainName: 'meter', chainId: 82, chainName: null },
    { fetchedChainName: 'vechain', chainId: 100009, chainName: null },
    { fetchedChainName: 'tomochain', chainId: 88, chainName: null },
    { fetchedChainName: 'world-chain', chainId: 480, chainName: 'worldChain' },
    { fetchedChainName: 'enuls', chainId: 119, chainName: null },
    { fetchedChainName: 'platon-network', chainId: 210425, chainName: null },
    { fetchedChainName: 'moonbeam', chainId: 1284, chainName: null },
    { fetchedChainName: 'moonchain', chainId: 18686, chainName: null },
    { fetchedChainName: 'taraxa', chainId: 841, chainName: null },
    { fetchedChainName: 'lung-chain', chainId: 78887, chainName: null },
    { fetchedChainName: 'maxxchain', chainId: 10201, chainName: null },
    { fetchedChainName: 'graphlinq-chain', chainId: 614, chainName: null },
    { fetchedChainName: 'pulsechain', chainId: 369, chainName: null },
    { fetchedChainName: 'multivac', chainId: 62621, chainName: null },
    { fetchedChainName: 'inevm', chainId: 2525, chainName: null },
    { fetchedChainName: 'larissa', chainId: 9898, chainName: null },
    { fetchedChainName: 'combo', chainId: 9980, chainName: null },
    { fetchedChainName: 'redstone', chainId: 690, chainName: null },
    { fetchedChainName: 'scroll', chainId: 534352, chainName: 'scroll' },
    { fetchedChainName: 'dogechain', chainId: 2000, chainName: 'dogechain' },
    { fetchedChainName: 'shiden network', chainId: 336, chainName: null },
    { fetchedChainName: 'cronos-zkevm', chainId: 388, chainName: null },
    { fetchedChainName: 'x-layer', chainId: 196, chainName: 'xLayer' },
    { fetchedChainName: 'sei-network', chainId: null, chainName: null },
    { fetchedChainName: 'axelar', chainId: null, chainName: null },
    { fetchedChainName: '8bit-chain', chainId: null, chainName: null },
    { fetchedChainName: 'qubic', chainId: null, chainName: null },
    { fetchedChainName: 'chia', chainId: null, chainName: null },
    { fetchedChainName: 'sei-v2', chainId: 1329, chainName: null },
    { fetchedChainName: 'apechain', chainId: 33139, chainName: null },
    { fetchedChainName: 'kroma', chainId: 255, chainName: null },
    { fetchedChainName: 'skale', chainId: 2046399126, chainName: null },
    { fetchedChainName: 'wax', chainId: null, chainName: null },
    { fetchedChainName: 'bsquared-network', chainId: null, chainName: null },
    { fetchedChainName: 'defiverse', chainId: 16116, chainName: null },
    { fetchedChainName: 'cosmos', chainId: null, chainName: null },
    { fetchedChainName: 'polkadot', chainId: null, chainName: null },
    { fetchedChainName: 'gravity-alpha', chainId: 1625, chainName: null },
    { fetchedChainName: 'bob-network', chainId: null, chainName: null },
    { fetchedChainName: 'starknet', chainId: null, chainName: null },
    { fetchedChainName: 'airdao', chainId: 16718, chainName: null },
    { fetchedChainName: 'klay-token', chainId: 8217, chainName: null },
    {
        fetchedChainName: 'binance-smart-chain',
        chainId: 56,
        chainName: 'binance',
    },
    { fetchedChainName: '', chainId: 1923, chainName: null },
    { fetchedChainName: 'vana', chainId: 1480, chainName: null },
    { fetchedChainName: 'sonic', chainId: 146, chainName: 'sonic' },
    { fetchedChainName: 'duckchain', chainId: 5545, chainName: null },
    { fetchedChainName: 'algorand', chainId: null, chainName: null },
    { fetchedChainName: 'xrp', chainId: null, chainName: null },
    { fetchedChainName: 'fantom', chainId: 250, chainName: null },
    { fetchedChainName: 'avalanche', chainId: 43114, chainName: 'avalanche' },
    { fetchedChainName: 'cronos', chainId: 25, chainName: null },
    { fetchedChainName: 'arbitrum-one', chainId: 42161, chainName: 'arbitrum' },
    { fetchedChainName: 'polygon-pos', chainId: 137, chainName: 'polygon' },
    { fetchedChainName: 'base', chainId: 8453, chainName: 'base' },
]